### ISSUE TITLE
无法显示玩家ID

### ISSUE THREAD

**Issue by pangys** [LegendOfMCPE/HealthBar#14]
用了这个插件后，HealthBar显示正常，但是玩家ID无法显示

**Comment by PEMapModder** [comment]
甚麼是玩家id？ 您是指玩家的名字？

**Comment by pangys** [comment]
嗯，是的。玩家名字处是一片黑...

**Comment by PEMapModder** [comment]
@iksaku translation:

> @pangys: After using this plugin, HealthBar displays normally, but player ID is unable to display
> @PEMapModder: What is player ID? You mean player's name?
> @pangys: hmm, yes. Player's name's location is a piece of darkness...

Please correct me if I translated wrongly.

**Comment by pangys** [comment]
It's right.Thanks.

**Comment by PEMapModder** [comment]
可以上載您的 `plugins/HealthBar/config.yml` 嗎？

Can you upload your `plugins/HealthBar/config.yml`?

**Comment by pangys** [comment]
不好意思，这几天有些事不能及时恢复。

config.yml我好像没有修改，但是我找不到了，因为我删掉了:(
但是我可以提供一下错误提示：
<code>[CRITICAL] Could not pass event pocketmine\event\entity\EntityDamageEvent to HealthBar v1.0.0: Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined on HealthBar\EventHandler</code>
<code>[NOTICE] InvalidArgumentException: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" (E_RECOVERABLE_ERROR) in "/HealthBar.phar/src/HealthBar/EventHandler" at line 60
</code>

**Comment by PEMapModder** [comment]
您是否在使用較舊的版本？這問題應該在很久前已經解決了。
