### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ghost** [LegendOfMCPE/HealthBar#18]
[Server thread/CRITICAL]: pocketmine\plugin\PluginException: "pocketmine\event\entity\EntityDamageByEntityEvent does not have a handler list" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 790

**Comment by SOF3** [comment]
Already fixed in 0cde0047f681ae746d34ab1d5df620d744da7e72... This is a bug that was fixed 27 months ago :joy:

**Comment by ghost** [comment]
Lol. I think I had an old version from PocketMine Forums... Sorry bro.
