### ISSUE TITLE
[ERROR] 'Could not load...'

### ISSUE THREAD

**Issue by Pausbacke** [LegendOfMCPE/HealthBar#9]
Hello LegendOfMCPE,

after placing your plugin I get following error:

[ERROR] Could not load '.../PocketMine-MP/plugins/HealthBar.phar' in folder '.../PocketMine-MP/plugins/': internal corruption of phar ".../PocketMine-MP/plugins/HealthBar.phar" (truncated entry)

Is this a problem with my end or the plugin?
Best regards

**Comment by PEMapModder** [comment]
Thanks for reporting properly :+1: ☺

Can you upload your downloaded version?

**Comment by Pausbacke** [comment]
How can I do so? Tried dragging, dropping and selecting but none worked...

**Comment by PEMapModder** [comment]
Can you use an external mirror like Dropbox?

**Comment by Pausbacke** [comment]
Doh!  :D
https://www.dropbox.com/s/pttzsg1ez3s7368/HealthBar.phar

**Comment by PEMapModder** [comment]
@Pausbacke redownload the plugin. An error occurred when you were downloading the plugin, and your plugin is empty. The plugin is 17 KB, but you uploaded a version with 0 bytes
